Repository rust-lang/docs.rs, pull requests merged in 2020-12, with the labels that each got.

#1209 Switch GitHub updates to GraphQL, part 2
  src/bin/cratesfyi.rs
  src/config.rs
  src/db/add_package.rs
  src/docbuilder/rustwide_builder.rs
  src/test/fakes.rs
  src/utils/daemon.rs
  src/utils/github_updater.rs
  src/web/crate_details.rs
  src/web/releases.rs
  templates/crate/details.html
  templates/rustdoc/topbar.html
Labels: S-waiting-on-deploy

#1189 Document that most targets are cross-compiled
  templates/core/about/builds.html
Labels: A-builds, C-doc, S-waiting-on-review

#1203 Fix behavior on menu bar with focus and active
  templates/style/_navbar.scss
Labels: A-docs-rs-themes, S-waiting-on-author

#1227 Fix "I am feeling lucky" after the GraphQL switch
  src/web/releases.rs
Labels: S-waiting-on-review

#1226 Add ayu-highlight.css
  .gitignore
  static/ayu-highlight.css
  templates/macros.html
Labels: A-docs-rs-themes, S-waiting-on-author

#1232 Tune and add breakpoints for the navbar to address overflow issues under certain conditions.
  templates/header/topbar_begin.html
  templates/rustdoc/topbar.html
  templates/style/_navbar.scss
Labels: S-waiting-on-review
