Repository rust-lang/docs.rs, pull requests merged in 2020-07, with the labels that each got.

#881 Link to documentation, not to /crate on homepage
  src/web/releases.rs
  tera-templates/core/home.html
Labels: A-frontend, P-high, S-waiting-on-review

#882 Fix links for releases page
  src/web/releases.rs
  tera-templates/releases/feed.xml
  tera-templates/releases/releases.html
Labels: A-frontend, P-high, S-waiting-on-review

#873 Don't munge window.location.hash to fix scroll positions
  templates/rustdoc/page.html
  templates/style.scss
Labels: A-frontend, P-medium, S-waiting-on-review

#890 Fixed details dropdown
  src/web/badge/src/lib.rs
  src/web/crate_details.rs
  templates/macros.html
Labels: A-frontend, C-bug, S-waiting-on-review

#891 Reduce code duplication for releases page
  src/web/releases.rs
Labels: A-backend, A-crate-search, C-technical-debt, P-low, S-waiting-on-review

#895 Fix 1.45 clippy warnings
  src/docbuilder/crates.rs
Labels: E-easy, P-high

#908 Move postgres to a non-default port
  .env.sample
  README.md
  docker-compose.yml
Labels: A-newcomer-roadblock, C-enhancement, S-waiting-on-review

#913 Add rustfmt when installing a new toolchain
  src/db/pool.rs
  src/docbuilder/rustwide_builder.rs
Labels: A-builds, C-enhancement, S-waiting-on-review

#901 Use a custom environment variable to configure logging
  .env.sample
  dockerfiles/entrypoint.sh
  src/bin/cratesfyi.rs
  src/test/mod.rs
Labels: A-newcomer-roadblock, S-waiting-on-review
