Repository rust-lang/docs.rs, pull requests merged in 2020-10, with the labels that each got.

#1079 Make crates page closer to rustdoc pages.
  templates/rustdoc/header.html
  templates/style/base.scss
Labels: A-frontend

#1080 Fix help blurring whole page
  templates/style/base.scss
Labels: A-frontend

#1081 Make crate menu onclick rather than onhover.
  templates/rustdoc/header.html
Labels: A-frontend

#1083 Fix clippy warnings
  src/storage/mod.rs
  src/utils/queue_builder.rs
  src/web/releases.rs
  src/web/rustdoc.rs
Labels: S-waiting-on-deploy

#1086 Show READMEs even if the build fails
  templates/crate/details.html
Labels: A-frontend, C-bug, S-waiting-on-review

#1097 menus: Tweak JS handling of clicks.
  static/menu.js
Labels: A-frontend, S-waiting-on-review

#1106 Redirect /proc-macro to /proc_macro
  src/web/mod.rs
  src/web/routes.rs
Labels: A-backend, S-waiting-on-review

#1107 Fix display of error messages
  templates/error.html
Labels: A-frontend, S-waiting-on-review

#1112 Update iron -> 0.6
  Cargo.lock
  Cargo.toml
  src/web/mod.rs
Labels: A-backend, C-technical-debt, S-waiting-on-deploy

#1109 Add favicon to essential files
  src/docbuilder/rustwide_builder.rs
Labels: S-waiting-on-review

#1110 Update prometheus, removing spin dependency
  Cargo.lock
  Cargo.toml
Labels: C-technical-debt, P-low, S-waiting-on-deploy

#1113 Add missing file in rerun-if-changed
  build.rs
Labels: A-newcomer-roadblock, C-bug, S-waiting-on-deploy

#1108 Move 'migrate' before 'build crate' in the README
  README.md
Labels: A-newcomer-roadblock, S-waiting-on-review

#1115 Fix error handling for search
  src/web/mod.rs
  src/web/releases.rs
Labels: S-waiting-on-review

#1117 Use walkdir to ensure all style files trigger rebuilding
  Cargo.toml
  build.rs
Labels: A-newcomer-roadblock, S-waiting-on-author

#1128 Fix typo in doc comment
  crates/metadata/lib.rs
Labels: S-waiting-on-deploy

#1134 Improve warnings display
  templates/style/_themes.scss
  templates/style/_utils.scss
Labels: A-docs-rs-themes, A-frontend, S-waiting-on-review

#1139 Use a minimal stylesheet for the navbar on rustdoc pages
  build.rs
  src/web/statics.rs
  templates/rustdoc/head.html
  templates/style/_fa.scss
  templates/style/_navbar.scss
  templates/style/base.scss
  templates/style/rustdoc.scss
Labels: A-frontend, S-waiting-on-review

#1129 Store feature flags per release in database
  Cargo.lock
  Cargo.toml
  src/db/add_package.rs
  src/db/migrate.rs
  src/db/mod.rs
  src/db/types.rs
  src/test/fakes.rs
  src/utils/cargo_metadata.rs
Labels: A-builds, C-enhancement, S-waiting-on-deploy

#1137 Fix top navbar resize
  templates/header/topbar_begin.html
  templates/rustdoc/topbar.html
  templates/style/_navbar.scss
Labels: A-frontend, S-waiting-on-author

#1141 Do not scroll when closing the menu with space
  static/menu.js
Labels: A-frontend, S-waiting-on-deploy
