Repository rust-lang/docs.rs, pull requests merged in 2020-09, with the labels that each got.

#1022 ignore rustwide from Cargo's workspace
  Cargo.toml
Labels: A-builds

#1024 Add more instructions to get auto-update for templates
  README.md
Labels: A-backend, A-newcomer-roadblock, C-doc, S-waiting-on-deploy

#1034 Fix styling of the about page header
  templates/about-base.html
  templates/style/base.scss
Labels: A-frontend

#1036 Don't crash if trying to move directories for a target that failed
  src/docbuilder/rustwide_builder.rs
Labels: A-builds, C-bug, S-waiting-on-deploy

#1020 Disable per-crate search now that rustdoc bugs are fixed
  src/docbuilder/rustwide_builder.rs
Labels: A-builds, A-frontend, S-waiting-on-review

#1045 Display "Go to latest stable" for pre-release
  src/web/mod.rs
  src/web/rustdoc.rs
  templates/rustdoc/header.html
Labels: A-backend, S-waiting-on-review

#1046 Add `impl From<Nope> for IronError` and use it across the codebase
  src/web/crate_details.rs
  src/web/error.rs
  src/web/file.rs
  src/web/releases.rs
  src/web/routes.rs
  src/web/rustdoc.rs
  src/web/source.rs
  src/web/statics.rs
Labels: A-backend, C-technical-debt, S-waiting-on-review

#1041 Rename crates to be in the same top-level crates/ directory
  Cargo.toml
  crates/badge/CHANGELOG.md
  crates/badge/Cargo.toml
  crates/badge/DejaVuSans.ttf
  crates/badge/LICENSE
  crates/badge/src/lib.rs
  crates/badge/test.svg
  crates/badge/test_badge.svg
  crates/metadata/Cargo.toml
  crates/metadata/build.rs
  crates/metadata/lib.rs
  dockerfiles/Dockerfile
Labels: C-technical-debt, S-waiting-on-review

#1052 Revert #1043 until I come up with a more principled fix for #1051
  src/web/error.rs
  src/web/mod.rs
Labels: A-backend, P-high, S-waiting-on-deploy

#1056 Only show rustdoc styles on rustdoc pages
  templates/base.html
  templates/rustdoc/head.html
Labels: A-frontend, S-waiting-on-review

#1060 Keep URL query when going to the latest version
  src/web/rustdoc.rs
Labels: A-backend, S-waiting-on-review

#1059 Fix rustdoc styles for very old docs
  src/utils/html.rs
Labels: A-frontend, S-waiting-on-review

#1063 Redirect to documentation in the version link
  src/web/rustdoc.rs
  templates/crate/details.html
  templates/macros.html
  templates/rustdoc/header.html
Labels: A-backend, S-waiting-on-review

#1069 Make more fields non-null
  src/db/migrate.rs
Labels: C-technical-debt, S-waiting-on-review
