Repository rust-lang/docs.rs, pull requests merged in 2020-08, with the labels that each got.

#932 Log when a file is not served because it was too big
  src/web/rustdoc.rs
Labels: A-admin, P-low, S-waiting-on-review

#931 Don't require rustfmt for the very first build
  src/docbuilder/rustwide_builder.rs
Labels: A-builds, A-newcomer-roadblock, C-enhancement, S-waiting-on-review

#936 Log HTML rewriting errors
  Cargo.lock
  src/utils/html.rs
  src/web/metrics.rs
  src/web/rustdoc.rs
Labels: A-admin, A-backend, P-low

#941 [Refactor] Changed GithubUpdater::new to use a HeaderMap instead of recollecting
  src/utils/github_updater.rs
Labels: A-backend, P-low, S-waiting-on-review

#942 Update README
  README.md
Labels: A-newcomer-roadblock, C-enhancement, P-medium, S-waiting-on-review

#946 Remove CSS files that shouldn't be on rustdoc pages
  templates/rustdoc/head.html
Labels: A-frontend, S-waiting-on-review

#951 Update `cargo run` commands
  README.md
Labels: A-newcomer-roadblock, S-waiting-on-review

#953 Add the Context trait and move Metrics out of the global state
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  src/bin/cratesfyi.rs
  src/build_queue.rs
  src/context.rs
  src/db/mod.rs
  src/db/pool.rs
  src/docbuilder/rustwide_builder.rs
  src/lib.rs
  src/metrics/macros.rs
  src/metrics/mod.rs
  src/storage/database.rs
  src/storage/mod.rs
  src/storage/s3.rs
  src/test/mod.rs
  src/utils/daemon.rs
  src/utils/queue_builder.rs
  src/web/extensions.rs
  src/web/metrics.rs
  src/web/mod.rs
  src/web/rustdoc.rs
Labels: C-technical-debt, S-waiting-on-author

#961 Improve the styling of the coverage in the dropdown
  src/test/fakes.rs
  src/web/mod.rs
  templates/crate/details.html
  templates/rustdoc/body.html
Labels: A-frontend, S-waiting-on-review

#954 Rework About/Build
  templates/core/about/builds.html
Labels: A-frontend, S-waiting-on-author

#965 Retain crate details padding on mobile screens
  templates/style/base.scss
Labels: A-frontend, S-waiting-on-review

#974 Fix readme
  README.md
Labels: A-newcomer-roadblock, C-bug

#972 Don't create a duplicate title on rustdoc pages
  templates/rustdoc/head.html
Labels: A-frontend, C-bug, S-waiting-on-review

#973 pre-commit hooks
  .git_hooks/pre-commit
  README.md
Labels: A-newcomer-roadblock, C-enhancement, S-waiting-on-author

#975 Run git gc periodically on the crates.io index
  src/config.rs
  src/docbuilder/queue.rs
  src/index/mod.rs
  src/utils/daemon.rs
Labels: A-admin, C-enhancement, S-waiting-on-author

#976 Improve logging & cexpect BuildPage.metadata
  src/web/builds.rs
  src/web/mod.rs
  src/web/page/web_page.rs
Labels: A-backend, S-waiting-on-review

#982 Move rustdoc header out of rustdoc container (Fixes #935)
  src/utils/html.rs
  templates/rustdoc/body.html
  templates/rustdoc/header.html
Labels: A-backend, C-bug, S-waiting-on-author

#983 update latest version calculation
  src/web/crate_details.rs
  src/web/rustdoc.rs
Labels: A-backend, S-waiting-on-deploy

#1010 RFC -> MCP
  mcps/migrate-to-async-hyper.md
  mcps/rework-index-updates.md
Labels: P-low, S-waiting-on-review

#1012 Fix clippy warnings in 1.46.0
  src/utils/queue.rs
  src/web/crate_details.rs
  src/web/mod.rs
  src/web/releases.rs
  src/web/sitemap.rs
Labels: C-technical-debt, S-waiting-on-review

#1017 Update to lockfile version 2
  Cargo.lock
Labels: C-technical-debt, S-waiting-on-review
