Repository rust-lang/docs.rs, pull requests merged in 2020-11, with the labels that each got.

#1154 Improve the navbar resize when not on a crate documentation
  templates/header/topbar_begin.html
Labels: A-frontend

#1157 Add fonts to static folder
  static/FiraSans-LICENSE.txt
  static/FiraSans-Medium.woff
  static/FiraSans-Regular.woff
  static/SourceCodePro-LICENSE.txt
  static/SourceCodePro-Regular.woff
  static/SourceCodePro-Semibold.woff
  static/SourceSerifPro-Bold.ttf.woff
  static/SourceSerifPro-It.ttf.woff
  static/SourceSerifPro-LICENSE.md
  static/SourceSerifPro-Regular.ttf.woff
  templates/style/base.scss
Labels: A-frontend, S-waiting-on-review

#1160 Remove whitespace beside docs.rs text
  templates/header/topbar_begin.html
Labels: A-frontend, S-waiting-on-review

#1169 Retain fragments when switching to different versions/platforms of the docs
  static/index.js
  templates/macros.html
  templates/rustdoc/topbar.html
Labels: S-waiting-on-review

#1164 Fix contrast on pure-css menu link when hover
  templates/style/_navbar.scss
Labels: A-frontend, S-waiting-on-review

#1183 Remove whitespace beside docs.rs text
  templates/rustdoc/topbar.html
Labels: A-frontend, S-waiting-on-review

#1186 Fix requesting non-ascii files
  src/web/rustdoc.rs
Labels: A-frontend, S-waiting-on-review

#1190 Don't crash on empty search queries
  src/web/releases.rs
Labels: S-waiting-on-review

#1136 Fix platform handling
  src/web/mod.rs
  templates/header/package_navigation.html
  templates/rustdoc/topbar.html
Labels: A-backend, C-bug, S-waiting-on-review

#1187 Add .rustwide to .gitignore
  .gitignore
Labels: A-newcomer-roadblock, S-waiting-on-review

#1145 Add a way to not build tier one targets by default
  .env.sample
  crates/metadata/lib.rs
  src/config.rs
  src/docbuilder/rustwide_builder.rs
Labels: A-builds, C-enhancement, S-waiting-on-review

#1195 Regression prevention
  src/web/mod.rs
Labels: A-frontend
