Repository rust-lang/docs.rs, pull requests merged in 2021-04, with the labels that each got.

#1307 Lock queue if updating toolchain fails
  src/docbuilder/queue.rs
Labels: A-builds, S-waiting-on-author

#1333 Add a Content Security Policy to non-rustdoc pages
  Cargo.lock
  Cargo.toml
  src/config.rs
  src/web/csp.rs
  src/web/mod.rs
  src/web/page/web_page.rs
  src/web/rustdoc.rs
  templates/base.html
  templates/core/home.html
  templates/crate/details.html
  templates/crate/features.html
  templates/macros.html
  templates/releases/activity.html
  templates/releases/releases.html
  templates/style/_utils.scss
Labels: A-frontend, S-waiting-on-review

#1340 Upload exactly the shared files needed and give precedence to global files over local ones
  src/docbuilder/rustwide_builder.rs
  src/utils/copy.rs
  src/utils/mod.rs
  src/web/mod.rs
Labels: S-waiting-on-review

#1343 Improve error message when feature flags aren't available
  templates/crate/features.html
Labels: A-frontend, S-waiting-on-review

#1350 Handle 404s and semver in source file viewer
  src/test/mod.rs
  src/web/mod.rs
  src/web/source.rs
Labels: S-waiting-on-review

#1249 Add gitlab repositories information retrieval
  Cargo.lock
  Cargo.toml
  README.md
  src/bin/cratesfyi.rs
  src/config.rs
  src/context.rs
  src/db/add_package.rs
  src/db/migrate.rs
  src/docbuilder/rustwide_builder.rs
  src/lib.rs
  src/repositories/github.rs
  src/repositories/gitlab.rs
  src/repositories/mod.rs
  src/repositories/updater.rs
  src/test/fakes.rs
  src/test/mod.rs
  src/utils/daemon.rs
  src/utils/github_updater.rs
  src/utils/mod.rs
  src/web/crate_details.rs
  src/web/extensions.rs
  src/web/releases.rs
  src/web/rustdoc.rs
  templates/crate/details.html
  templates/rustdoc/topbar.html
Labels: A-backend, S-waiting-on-deploy

#1268 Fixes #1267 - fix handling of github graphql errors
  src/repositories/github.rs
Labels: S-waiting-on-review

#1365 Reduce logging at startup
  src/config.rs
Labels: A-newcomer-roadblock

#1372 Remove GITHUB_USERNAME from the readme
  README.md
Labels: S-waiting-on-review

#1374 Add support for cargo-args in package metadata
  crates/metadata/lib.rs
  templates/core/Cargo.toml.example
Labels: A-builds, S-waiting-on-review

#1367 Add footer
  templates/base.html
  templates/core/about/badges.html
  templates/core/about/builds.html
  templates/core/about/index.html
  templates/core/about/metadata.html
  templates/core/about/redirections.html
  templates/footer.html
  templates/header/topbar_begin.html
  templates/rustdoc/body.html
  templates/style/_navbar.scss
  templates/style/_vars.scss
  templates/style/base.scss
  templates/style/footer.scss
  templates/style/rustdoc.scss
Labels: S-waiting-on-review
