Repository rust-lang/docs.rs, pull requests merged in 2021-09, with the labels that each got.

#1342 compressed storage for rustdoc- and source-files
  .github/workflows/ci.yml
  .gitignore
  Cargo.lock
  Cargo.toml
  benches/compression.rs
  docker-compose.yml
  src/bin/cratesfyi.rs
  src/config.rs
  src/db/add_package.rs
  src/db/file.rs
  src/db/migrate.rs
  src/db/mod.rs
  src/docbuilder/rustwide_builder.rs
  src/storage/archive_index.rs
  src/storage/compression.rs
  src/storage/database.rs
  src/storage/mod.rs
  src/storage/s3.rs
  src/test/fakes.rs
  src/test/mod.rs
  src/web/crate_details.rs
  src/web/file.rs
  src/web/rustdoc.rs
  src/web/source.rs
Labels: S-waiting-on-review, A-builds, A-backend

#1490 If the build fails with the published Cargo.lock, try removing it and retrying
  src/docbuilder/rustwide_builder.rs
Labels: S-waiting-on-review, A-builds, C-enhancement

#1491 Sort (and display) releases by build time, not release time
  src/web/releases.rs
  templates/core/home.html
  templates/releases/feed.xml
  templates/releases/releases.html
Labels: S-waiting-on-review, A-backend

#1505 also delete archives and indexes when deleting crates and indexes
  src/bin/cratesfyi.rs
  src/db/delete.rs
Labels: A-admin
