Repository rust-lang/docs.rs, pull requests merged in 2021-11, with the labels that each got.

#1540 Remove pubsub integration
  src/build_queue.rs
  src/utils/mod.rs
  src/utils/pubsubhubbub.rs
  src/utils/queue_builder.rs
Labels: S-waiting-on-review

#1550 ignore audit advisories we want to ignore, or cannot do anything right now
  .cargo/audit.toml
  .github/workflows/audit.yml
Labels: S-waiting-on-review

#1551 don't upload to docker in forked repos
  .github/workflows/docker.yml
Labels: S-waiting-on-review

#1554 remove unnecessary dereferences
  src/bin/cratesfyi.rs
Labels: S-waiting-on-review

#1557 Remove unused `foreground` argument to `daemon`
  src/bin/cratesfyi.rs
Labels: S-waiting-on-review

#1527 Serve /crate/latest/crate rather than redirect
  src/web/build_details.rs
  src/web/builds.rs
  src/web/crate_details.rs
  src/web/features.rs
  src/web/mod.rs
  src/web/rustdoc.rs
  src/web/source.rs
  templates/header/package_navigation.html
  templates/rustdoc/topbar.html
Labels: S-waiting-on-author

#1559 Fix compiling for x86_64-unknown-linux-gnu when it's not the default target
  crates/metadata/lib.rs
  src/docbuilder/rustwide_builder.rs
Labels: S-waiting-on-review, A-builds

#1565 Generate lockfile and fetch dependencies outside sandbox on retry
  src/docbuilder/rustwide_builder.rs
Labels: C-bug, S-waiting-on-author, A-builds

#1546 change latest version ID on crate to match CrateDetails.latest_version
  src/db/add_package.rs
  src/db/migrate.rs
  src/test/mod.rs
  src/web/crate_details.rs
  src/web/mod.rs
  src/web/rustdoc.rs
Labels: S-waiting-on-deploy

#1567 use precalculated latest version in search-results
  src/web/releases.rs
Labels: S-waiting-on-deploy
