Repository rust-lang/docs.rs, pull requests merged in 2021-06, with the labels that each got.

#1363 Fix "go to latest version" for /src/ when an item was renamed
  src/test/fakes.rs
  src/web/mod.rs
  src/web/rustdoc.rs
Labels: A-backend, S-waiting-on-author

#1423 fix new clippy warnings
  crates/font-awesome-as-a-crate/build.rs
  src/build_queue.rs
  src/db/add_package.rs
  src/docbuilder/rustwide_builder.rs
  src/repositories/updater.rs
  src/web/build_details.rs
  src/web/builds.rs
  src/web/crate_details.rs
  src/web/features.rs
  src/web/rustdoc.rs
  src/web/source.rs
Labels: S-waiting-on-review

#1420 Update the README
  README.md
Labels: S-waiting-on-review

#1427 Don't loop forever if the template fails to render
  src/web/page/web_page.rs
Labels: A-backend, S-waiting-on-review

#1424 Don't read Cargo.toml.orig
  crates/metadata/lib.rs
Labels: A-builds, S-waiting-on-review

#1419 Fix syntax error when rendering topbar for source page
  src/web/source.rs
  templates/rustdoc/topbar.html
Labels: A-backend, S-waiting-on-review

#1426 Fix crash when clicking "go to latest" on non-rust file that was deleted
  src/web/rustdoc.rs
Labels: A-backend, S-waiting-on-review

#1429 extend readme to include how to run builds on non-linux systems
  README.md
Labels: S-waiting-on-review

#1432 Give a hard error if outdated environment variables are set
  src/config.rs
Labels: S-waiting-on-review

#1437 Remove `<span class="title">` around `Source` link on dropdown
  templates/rustdoc/topbar.html
Labels: S-waiting-on-review

#1433 Don't spam migrating logs when running tests
  .env.sample
  src/db/migrate.rs
Labels: A-newcomer-roadblock, S-waiting-on-review

#1440 Make initialization for BinContext easier to read
  src/bin/cratesfyi.rs
Labels: C-technical-debt, S-waiting-on-review
