Repository rust-lang/docs.rs, pull requests merged in 2021-03, with the labels that each got.

#1301 Add crates.js and woff2 fonts to required files
  src/docbuilder/rustwide_builder.rs
Labels: S-waiting-on-deploy

#1304 Fix nightly warnings
  src/docbuilder/mod.rs
  src/utils/github_updater.rs
  src/web/crate_details.rs
  src/web/page/templates.rs
Labels: C-technical-debt, S-waiting-on-review

#1315 Fix code blocks in `/about`
  templates/core/about/builds.html
  templates/core/about/metadata.html
Labels: S-waiting-on-review

#1324 Give precedence to local shared files over global ones
  src/web/mod.rs
Labels: A-backend, A-builds, S-waiting-on-review

#1312 Don't hard-code essential rustdoc files
  src/docbuilder/rustwide_builder.rs
  src/utils/copy.rs
Labels: A-builds, S-waiting-on-review

#1326 Remove `database_file_handler`; give precendence to router error messages
  src/web/error.rs
  src/web/file.rs
  src/web/metrics.rs
  src/web/mod.rs
  src/web/rustdoc.rs
Labels: A-backend, S-waiting-on-deploy

#1322 stop displaying and serving authorship information
  src/web/error.rs
  src/web/releases.rs
  src/web/routes.rs
  templates/crate/details.html
  templates/releases/header.html
  templates/releases/releases.html
  templates/rustdoc/topbar.html
Labels: S-waiting-on-author

#1330 Serve rust-logo.png as a shared file
  src/web/rustdoc.rs
Labels: A-backend

#1332 Reland rustwide and tokio upgrade
  Cargo.lock
  Cargo.toml
  crates/badge/Cargo.toml
  src/storage/s3.rs
Labels: S-waiting-on-review

#1314 Cleanup unneeded JS
  static/menu.js
  templates/core/home.html
Labels: A-frontend, C-technical-debt, S-waiting-on-author
