Repository rust-lang/docs.rs, pull requests merged in 2021-02, with the labels that each got.

#1271 Add anchor links to headers
  templates/core/about/builds.html
  templates/core/about/index.html
Labels: C-doc, S-waiting-on-author

#1275 Add left and right margin to center about container
  templates/core/about/badges.html
  templates/core/about/builds.html
  templates/core/about/index.html
  templates/core/about/metadata.html
  templates/core/about/redirections.html
Labels: A-frontend, S-waiting-on-author

#1259 Improve topbar crate dropdown menu by removing uneeded information
  templates/rustdoc/topbar.html
  templates/style/_navbar.scss
Labels: S-waiting-on-review

#1278 Revert "Upgrade rusoto (and tokio)"
  Cargo.lock
  Cargo.toml
  src/storage/s3.rs
Labels: A-admin, S-waiting-on-review

#1279 Don't execute a build when not enough memory is available
  src/config.rs
  src/docbuilder/rustwide_builder.rs
Labels: A-admin, A-builds, S-waiting-on-review

#1282 Update comrak to 0.9.1
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-review
