Repository rust-lang/docs.rs, pull requests merged in 2021-01, with the labels that each got.

#1233 Fix sidebar rendering bugs
  templates/style/rustdoc.scss
Labels: A-frontend, S-waiting-on-author

#1236 Validate requested crate version when rendering the build and feature views
  src/web/builds.rs
  src/web/features.rs
Labels: A-backend, S-waiting-on-deploy

#1237 fix performance regression in all releases-views
  src/db/migrate.rs
  src/web/releases.rs
Labels: S-waiting-on-deploy

#1245 Use target-redirect for latest version redirect
  src/web/rustdoc.rs
Labels: S-waiting-on-deploy

#1255 Switch to chart.js for the release activity page
  templates/releases/activity.html
  vendor/chartjs/LICENSE
  vendor/chartjs/chart.min.css
  vendor/chartjs/chart.min.js
Labels: S-waiting-on-deploy

#1254 change URLs in releases-pages to remove unnecessary redirect
  src/web/releases.rs
  templates/core/home.html
  templates/releases/feed.xml
  templates/releases/releases.html
Labels: S-waiting-on-author

#1257 remove more unnecessary redirects in search-results, and i'm feeling-lucky
  src/web/releases.rs
Labels: A-backend, S-waiting-on-deploy

#1258 Make /crate/:crate/latest/builds.json not strip .json suffix
  src/web/builds.rs
Labels: A-backend, S-waiting-on-author

#1260 refactor random crate search, the random view size is configurable and we don't retry any more
  src/config.rs
  src/web/releases.rs
Labels: S-waiting-on-review
