Repository rust-lang/docs.rs, pull requests merged in 2021-08, with the labels that each got.

#1455 fix clippy warning on non-linux systems
  src/docbuilder/rustwide_builder.rs
Labels: S-waiting-on-review

#1456 replace deprecated failure library with anyhow and thiserror
  Cargo.lock
  Cargo.toml
  src/bin/cratesfyi.rs
  src/build_queue.rs
  src/config.rs
  src/context.rs
  src/db/blacklist.rs
  src/db/delete.rs
  src/db/pool.rs
  src/docbuilder/crates.rs
  src/docbuilder/rustwide_builder.rs
  src/error.rs
  src/index/api.rs
  src/index/crates.rs
  src/index/mod.rs
  src/metrics/mod.rs
  src/repositories/github.rs
  src/repositories/gitlab.rs
  src/repositories/mod.rs
  src/repositories/updater.rs
  src/storage/compression.rs
  src/storage/database.rs
  src/storage/mod.rs
  src/storage/s3.rs
  src/test/fakes.rs
  src/test/mod.rs
  src/utils/cargo_metadata.rs
  src/utils/consistency/db.rs
  src/utils/consistency/index.rs
  src/utils/consistency/mod.rs
  src/utils/daemon.rs
  src/utils/queue_builder.rs
  src/utils/rustc_version.rs
  src/web/crate_details.rs
  src/web/error.rs
  src/web/extensions.rs
  src/web/mod.rs
  src/web/page/templates.rs
  src/web/releases.rs
  src/web/rustdoc.rs
Labels: S-waiting-on-review

#1431 Fix indent level for build.rs example
  templates/core/Cargo.toml.example
  templates/core/about/builds.html
Labels: A-frontend, S-waiting-on-review

#1362 Redirect to shields.io instead of writing our own badges
  Cargo.lock
  Cargo.toml
  crates/badge/CHANGELOG.md
  crates/badge/Cargo.toml
  crates/badge/DejaVuSans.ttf
  crates/badge/LICENSE
  crates/badge/src/lib.rs
  crates/badge/test.svg
  crates/badge/test_badge.svg
  dockerfiles/Dockerfile
  src/test/mod.rs
  src/web/rustdoc.rs
  templates/core/about/badges.html
Labels: A-backend, S-waiting-on-deploy

#1475 Make it clear what's happening when `cargo run` hangs for 10 seconds
  src/db/pool.rs
Labels: A-newcomer-roadblock
