Repository rust-lang/docs.rs, pull requests merged in 2022-01, with the labels that each got.

#1582 fix duplicate error when adding a version to the build-queue
  src/build_queue.rs
Labels: S-waiting-on-deploy

#1579 Fix new sidebar changes
  build.rs
  src/utils/mod.rs
  src/utils/rustc_version.rs
  src/web/builds.rs
  src/web/crate_details.rs
  src/web/mod.rs
  src/web/source.rs
  src/web/statics.rs
  templates/rustdoc/head.html
  templates/style/rustdoc-2021-12-06.scss
  templates/style/rustdoc-common.scss
  templates/style/rustdoc.scss
Labels: S-waiting-on-review

#1601 daily purge of purge rustwide caches
  src/build_queue.rs
  src/docbuilder/rustwide_builder.rs
Labels: S-waiting-on-deploy

#1603 Allow to click on the footer again by positioning the footer on top of the main div
  templates/style/rustdoc-common.scss
Labels: S-waiting-on-author

#1604 Support either proc-macro or proc_macro keys
  crates/metadata/lib.rs
Labels: S-waiting-on-deploy

#1587 run cargo update
  Cargo.lock
Labels: S-waiting-on-deploy

#1606 Add styles for rustdoc mobile-topbar
  templates/style/rustdoc-common.scss
Labels: S-waiting-on-deploy

#1611 Add explicit padding-top: 0 to topbar body style
  templates/style/_navbar.scss
Labels: S-waiting-on-review

#1596 Remove JS workaround for scroll-padding-top
  templates/rustdoc/body.html
Labels: S-waiting-on-deploy

#1615 run cargo update
  Cargo.lock
Labels: S-waiting-on-review

#1616 remove hot template reloading
  Cargo.lock
  Cargo.toml
  README.md
  src/bin/cratesfyi.rs
  src/test/mod.rs
  src/utils/daemon.rs
  src/utils/html.rs
  src/web/mod.rs
  src/web/page/templates.rs
  src/web/page/web_page.rs
Labels: S-waiting-on-deploy

#1617 update `time` dependency in build-script
  Cargo.lock
  Cargo.toml
  build.rs
Labels: S-waiting-on-review

#1623 upgrade the rusoto libraries
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-deploy

#1621 upgrade mockito
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-deploy

#1622 upgrade sentry
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-deploy

#1620 retry S3 request for `storage.get` and `storage.exists`
  src/storage/s3.rs
Labels: S-waiting-on-review

#1618 Fix resize of top navbar
  templates/style/_navbar.scss
Labels: S-waiting-on-deploy

#1625 Add top and height settings for mobile sidebar
  templates/style/rustdoc-common.scss
Labels: S-waiting-on-review

#1645 upgrade crates-index-diff
  Cargo.lock
  Cargo.toml
  src/index/mod.rs
Labels: S-waiting-on-review

#1644 run `cargo update`
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-review

#1647 upgrade `env_logger`
  Cargo.lock
  Cargo.toml
  src/bin/cratesfyi.rs
  src/test/mod.rs
Labels: S-waiting-on-review

#1648 upgrade `comrak`
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-review

#1650 upgrade `rustwide`
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-review

#1649 upgrade `prometheus`
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-review

#1653 upgrade `strum`
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-review

#1654 upgrade `dashmap`
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-review

#1651 upgrade `zstd`
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-review
