Repository rust-lang/docs.rs, pull requests merged in 2022-09, with the labels that each got.

#1814 Assert that redirects go directly to their target location
  Cargo.lock
  Cargo.toml
  src/test/mod.rs
  src/web/crate_details.rs
  src/web/metrics.rs
  src/web/mod.rs
  src/web/releases.rs
  src/web/routes.rs
  src/web/rustdoc.rs
Labels: S-waiting-on-author

#1819 Update the section about `.env` in README.md
  README.md
Labels: S-waiting-on-review

#1789 retry toolchain update, only lock queue after 3 failed attempts
  src/build_queue.rs
Labels: S-waiting-on-review

#1569 Add Cache-Control to rustdoc pages
  src/config.rs
  src/web/rustdoc.rs
Labels: S-waiting-on-review

#1824 fix rustdoc caching tests
  src/web/rustdoc.rs
Labels: S-waiting-on-review

#1828 add more iron dependency "unmaintained" warnings to ignore-file
  .cargo/audit.toml
Labels: S-waiting-on-review

#1816 Retain queries and convert `::` paths on redirects to rust-lang.org
  src/web/mod.rs
  src/web/routes.rs
  src/web/rustdoc.rs
Labels: S-waiting-on-review

#1831 Remove `type="text/css"` from stylesheet links
  templates/base.html
  templates/macros.html
  templates/rustdoc/head.html
  templates/rustdoc/vendored.html
Labels: S-waiting-on-review

#1809 add clippy book to Rust dropdown menu
  templates/header/topbar_end.html
Labels: S-waiting-on-review

#1836 Fix weird menu bug when using down-arrow to open a menu
  static/menu.js
Labels: S-waiting-on-review

#1840 Set a minimum for last-modified in sitemap
  src/web/sitemap.rs
Labels: S-waiting-on-review

#1781 add priority and `all.html` to sitemap
  templates/core/sitemap.xml
Labels: S-blocked, S-waiting-on-review

#1838 Include slash at the end of sitemap URLs
  templates/core/sitemap.xml
Labels: S-waiting-on-review

#1841 Update Discord invite link on about page
  templates/core/about/index.html
Labels: S-waiting-on-review

#1820 Remove links that shouldn't be in the top navbar
  templates/header/topbar_end.html
Labels: S-waiting-on-review

#1835 Include all versions of a crate on recent + recent-failures pages
  src/web/releases.rs
Labels: S-waiting-on-review

#1843 fix performance regression after 644ebfd3 and 3868e79
  src/db/migrate.rs
  src/web/releases.rs
Labels: S-waiting-on-review

#1845 upgrade aws-sdk
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-review

#1846 run cargo update
  Cargo.lock
Labels: S-waiting-on-review

#1837 Fix `.env.sample` so it actually puts variables in the environment when sourced
  .env.sample
Labels: S-waiting-on-author

#1829 Add canonical link for crate pages
  src/web/crate_details.rs
  templates/crate/details.html
Labels: S-waiting-on-author

#1850 Add rel="nofollow" on Versions links
  templates/macros.html
Labels: S-waiting-on-review

#1830 keep queries when doing lucky, `::` or crate-name searches
  src/web/mod.rs
  src/web/releases.rs
  src/web/rustdoc.rs
Labels: S-waiting-on-author

#1855 get rid of empty url parameter section in some redirects
  src/web/mod.rs
  src/web/releases.rs
  src/web/rustdoc.rs
Labels: S-waiting-on-review

#1857 add `#[track_caller]` to test wrapper
  src/test/mod.rs
Labels: S-waiting-on-review

#1863 Update comment about buggy static file serving
  src/web/mod.rs
Labels: S-waiting-on-review
